# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: clisso
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: linux
    binary: clisso
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - "amd64"
      - "386"

  # The build-chain does not support CGO for ARM64 on Linux
  - id: unsupported-cgo
    binary: clisso
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "arm64"
    goarm:
      - "6"
      - "7"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
