apps:
  sample-app-1:
    app-id: "123456"
    principal-arn: arn:aws:iam::123456789012:saml-provider/OneLoginDev
    provider: sample-onelogin-provider
    role-arn: arn:aws:iam::123456789012:role/OneLoginDev-SSO
    arn: arn:aws:iam::012345678012:role/Dev
    aws-region: eu-west-1
    autodetect-yubikey: true
  sample-app-2:
    principal-arn: arn:aws:iam::123456789012:saml-provider/Okta
    provider: sample-okta-provider
    role-arn: arn:aws:iam::123456789012:role/OktaDevSSO
    url: https://xxxxxxxx.oktapreview.com/home/amazon_aws/xxxxxxxxxxxxxxxxxxxx/137
global:
  autodetect-yubikey: true
  aws-region: us-east-1
  output: ~/.aws/credentials
  selected-app: sample-app-1
  accounts:
    "0000000000000": Dev
    "1111111111111": Prod
    "2222222222222": QA
providers:
  sample-onelogin-provider:
    client-id: abcdef-sample-client-id-ghijkl
    client-secret: 123456-sample-client-secret-789012
    subdomain: sample
    type: onelogin
    username: example@example.com
  sample-okta-provider:
    base-url: https://xxxxxxxx.oktapreview.com
    type: okta
    username: example@example.com
