on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: run tests
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run linters
      uses: golangci/golangci-lint-action@v3
    - name: Check code formatting using gofmt
      uses: Jerome1337/gofmt-action@v1.0.5

  test:
    strategy:
      matrix:
        go: [stable, oldstable]
        platform: [ubuntu-latest , macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v4
      - name: Install Dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y gnome-keyring build-essential ca-certificates
          mkdir -p $HOME/.cache/
          mkdir -p $HOME/.local/share/keyrings/
          chmod 700 -R $HOME/.local/
        if: matrix.platform == 'ubuntu-latest'
      - name: tests (other)
        run: go test -v -coverprofile=profile ./...
        if: matrix.platform != 'ubuntu-latest'
      - name: tests (Linux)
        run: |
          echo 'somecredstorepass' | gnome-keyring-daemon --unlock
          go test -v -coverprofile=profile ./...
        shell: dbus-run-session -- bash --noprofile --norc -eo pipefail {0}
        if: matrix.platform == 'ubuntu-latest'

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile
          flag-name: Platform-${{ matrix.platform }}
          parallel: true
  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
